services:

  redis:
    image: redis:8

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: crawler
      POSTGRES_PASSWORD: crawler
      POSTGRES_DB: crawler_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql

  crawler:
    build: .
    image: distributed-crawler:latest
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_HOST: redis
      DB_HOST: postgres
      DB_USER: crawler
      DB_PASSWORD: crawler
      DB_NAME: crawler_db
      DB_PORT: 5432
      START_URL: http://host.docker.internal:3000/page/1
    deploy:
      replicas: 3

volumes:
  postgres_data:
